### ISSUE TITLE
SSP2Ariadne scenario distorts historic population figures 

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/mrremind#108]
From #107:
```
> calcOutput('Population', aggregate = FALSE, FiveYearSteps = FALSE) %>% 
+     `[`('FRA',1962,) %>% 
+     as.data.frame()

Run calcOutput(type = "Population", aggregate = FALSE, FiveYearSteps = FALSE)
~  - loading cache calcPopulation-F04e78c6a-aa608a57.rds
Exit calcOutput(type = "Population", aggregate = FALSE, FiveYearSteps = FALSE) in 0.09 seconds
   Cell Region Year           Data1    Value
1    NA    FRA 1962        pop_SSP1 47.90488
2    NA    FRA 1962        pop_SSP2 47.90488
3    NA    FRA 1962        pop_SSP3 47.90488
4    NA    FRA 1962        pop_SSP4 47.90488
5    NA    FRA 1962        pop_SSP5 47.90488
6    NA    FRA 1962         pop_SDP 47.90488
7    NA    FRA 1962      pop_SDP_EI 47.90488
8    NA    FRA 1962      pop_SDP_RC 47.90488
9    NA    FRA 1962      pop_SDP_MC 47.90488
10   NA    FRA 1962 pop_SSP2Ariadne 55.75089
```
Did the ARIADNE project include building a time machine?

**Comment by johanneskoch94** [comment]
So in general there will be slight differences between historic Ariadne and SSP numbers, because the Ariadne scenario uses Eurostat figures (for the European countries) while the SSPs and SDPs use figures from the World Bank. That way the Ariadne historic figures and projection (which are also from Eurostat) harmonize well in 2019. 
The problem here is that for numbers that far back, we sometimes extrapolate (and by extrapolate I mean keep konstant) from the last available data point. In this case the Eurostat data only goes until 1982, from which point on it is held constant. We could try getting further data (I mean the numbers must be available for EUR countries right?), or simple use WB growth rates. 

How big of a priority is this?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Kinda big.  This requires special treatment of the SSP2Ariadne scenario in every script dealing with historic figures …

**Comment by johanneskoch94** [comment]
Ok, I submitted a PR in mrcommons. For now I'm just using the WB growth rates.
