### ISSUE TITLE
General EDGE-Transport Breakdown

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/mrremind#231]
I'm reporting a couple of bugs and throw them in the general direction of you transport people, since I don't know who did what and I don't have time to sift through the logs right now.  Sorry about that.

**Comment by MariannaR** [comment]
thanks @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q ! It might be that the second bug you found is due to the cache failing on the first bug - the file `ptab4W.cs4r` is a new addition of this `mrremind` version, but probably the cache fails before producing it. Hence it cannot be loaded by the run. Will have a look at it together with @johannah-pik

**Comment by MariannaR** [comment]
Seems this issue is solved, thanks to all for the debugging :)
