### ISSUE TITLE
historical.mif: improve emissions data

### ISSUE THREAD

**Issue by robertpietzcker** [pik-piam/mrremind#409]
currently, we don't have aggregated industry emissions, only energy and process emissions separately.

so it would be great to add:

1. Emi|GHG|Industry = Emi|GHG|Industrial Processes + Emi|GHG|Energy|Demand|Industry
2. Emi|CO2|Industry =  Emi|CO2|Industrial Processes + Emi|CO2|Energy|Demand|Industry

**Comment by fbenke-pik** [comment]
Which Emission references / sources does this concern? 
In theory, I can do it for all models that provide both variables, but normally we would specify such additional calculations per-source and not universally. 

cc @Renato-Rodrigues

**Comment by robertpietzcker** [comment]
Good question!

CEDS has both
EDGAR6 has both
Eurostat has both
UNFCCC has both

so please implement it for these four sources :-)

**Comment by fbenke-pik** [comment]
> CEDS has both

As of now, we don't have  `Emi|GHG|Energy|Demand|Industry` to calculate `Emi|GHG|Industry`

**Comment by robertpietzcker** [comment]
what are we using as variable to calculate "Emi|CO2|Energy|Demand|Industry" - don't they have the same variable in a "all GHG" version?

anyway, if it is not there, it can't be added - it seems I only checked for UNFCCC and EUROSTAT for the GHG variant.

**Comment by fbenke-pik** [comment]
Never mind, I can calculate the missing variable from what's there.

**Comment by robertpietzcker** [comment]
@fbenke-pik sorry to bother you again about this - do you have any idea why in the latest historical.mif, UNFCCC again doesn't have "Emi|CO2|Industry" variable, although the variables used for the calculation (Emi|CO2|Industrial Processes and Emi|CO2|Energy|Demand|Industry) are there? (The Eurostat entries correctly show all 3 variables)

**Comment by fbenke-pik** [comment]
I just checked the latest inputdata from 24th February (p/projects/rd3mod/inputdata/output/rev6.70APT-2024-02-24_2b1450bc-980575d2_validationremind.tgz)

`Emi|CO2|Industry` is available for some regions, so it is calculated in principle. If it is missing for a specific region, then at least one of the summands is NA for this region.

The function hasn't been changed since October, so doesn't look like a bug caused values to disappear that used to be there.

**Comment by fbenke-pik** [comment]
Could you give me more specifics so I can investigate further?

**Comment by robertpietzcker** [comment]
yes :-)

I only see the aggregated variable for UNFCCC for countries (DEU, US in the image), but not for regions (EU27, CAZ), although the two summands (https://github.com/fbenke-pik/mrremind/blob/e5a7895d658de712a7ca828390c98403f288920f/R/calcEmissions.R#L297C1-L300C64 )
exist. 

Might it be something in the order of calculation region values?

![image](https://github.com/pik-piam/mrremind/assets/61154412/10e962c7-2d6e-440b-a5be-b5f7db528f6a)

**Comment by fbenke-pik** [comment]
EU27 might just be a simple bug that should be fixed with this mapping correction
https://github.com/pik-piam/piamMappings/commit/7096463d308354c47fec0045fd39f3a7aef7df35

ALA has NAs in the source, but was added to EU27, resulting in the whole region to be NA

For CAZ, this is a structural inconsistency.

- (A) For the variables we read in from UNFCCC, we set all missing countries to 0 to get values for regions ([source](https://github.com/pik-piam/mrremind/blob/master/R/convertUNFCCC.R#L33)). 
- (B) For the Emissions calculated later on, we use the opposite approach, i.e. we set NAs so regions will be NA if any country is NA (AUT in this case). 
- This explains why you have values for Emi|CO2|Industrial Processes and Emi|CO2|Energy|Demand|Industry (approach A), but not for Emi|CO2|Industry (approach B)

I can unify the approach to make it consistent, but there might be good reasons why we did it this way. Up to you to decide how to proceed.

**Comment by fbenke-pik** [comment]
> I can unify the approach to make it consistent, but there might be good reasons why we did it this way. Up to you to decide how to proceed.

One reason why we set 0 when calculating new variables was that some of the variables summing used for up can be NA, but the sum should still be calculated (e.g. Emi|CH4|Waste being NA should not lead to Emi|CH4 not being calculated).

If you need precise data for these variables, we will have to revisit the rules we apply and probably also decide per additional calculation of additional variables how to deal with NAs in the regional and variable dimensions.

**Comment by pweigmann** [comment]
I was just made aware of this discussion, as I was looking for globally aggregated emission data by UNFCCC.

The problem I see here is that we currently only have the data of the Annex I countries. If I understand correctly, the reporting standards are different between Annex I and II, so we only have really detailed data for [Annex I](https://unfccc.int/ghg-inventories-annex-i-parties/2023).

@robertpietzcker Would it be an option to combine what we already have with the ["GHG Profiles"](https://di.unfccc.int/ghg_profile_non_annex1) for the other countries? They are less detailed but exist for almost all countries. This would probably allow us to fill up some of the holes we create when aggregating regions without changing the general methodology, which I think works well for our current data situation.

**Comment by robertpietzcker** [comment]
So if I understand correctly, we should now see results for EU27, because you removed the one region without any values; however we will not see results for any regions that have Annex2 countries mixed in because they have limited reporting?

sounds not perfect, but the best we can do with the limited input data.

about the GHG profiles - I just opened the one for Afghanistan, and it has only 2005 and 2013 data. not sure how well we can use that (is it the same years for all countries, etc?), and if it is better than the CEDS/EDGAR data for these countries?

**Comment by pweigmann** [comment]
Yes, it seems there just is not a lot of data from Annex II countries, clicked through more and many didn't have data from the last 10 years. EDGAR definitely has more data there, CEDS too but it hasn't published any updates since 2021. So it seems the UNFCCC data is not useful for global aggregates.

@fbenke-pik I found this tool by Primap/Mika, not sure if it could be useful when we want to update UNFCCC data in the future?
https://github.com/mikapfl/unfccc_di_data

**Comment by fbenke-pik** [comment]
Nevermind what I said, i will for now add a solution that makes sure that the following regions are always produced by setting NAs to zero: "EUR", "REF", "NEU", "CAZ"

If values are too low, we can revisit

**Comment by fbenke-pik** [comment]
@robertpietzcker please check this file for consistency and missing variables: https://cloud.pik-potsdam.de/index.php/f/20051142

It corresponds to the changes in this PR: https://github.com/pik-piam/mrremind/pull/478

**Comment by Renato-Rodrigues** [comment]
I only saw this now, but as suggestion maybe for the future cases we could think about creating a function that automates regional aggregations considering only relevant regions based on an external data and a threshold.

For example, if we use gdp as our external data to define relevant regions, we could ignore any regions that contribute with less than 2% of the gdp for a given regional aggregation in the creation of the total regional values.

Something like:
`createRelevantAggregation(countryData, regionalMapping, weightVariable=gdp, thresholdPercentage=0.02)`  
if the country is less than 2% of the total region gdp, we don't consider it as missing data, but instead as zeros.
